name: Build robot code

on:
  pull_request:
    types: [opened, reoponed, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    # WPILib docker container
    container: wpilib/roborio-cross-ubuntu:2022-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Compile robot code to ensure it is working
      run: ./gradlew build
